#include "data/MarketData.hpp"
#include "indicators/Indicators.hpp"
#include "strategy/Strategy.hpp"
#include "execution/ExecutionEngine.hpp"
#include "portfolio/Portfolio.hpp"
#include "risk/RiskManager.hpp"
#include "backtest/BacktestEngine.hpp"
#include "performance/PerformanceAnalyzer.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <numeric>
#include <sstream>
#include <stdexcept>
namespace qte::data { std::vector<ValidationIssue> DataValidator::validate(const std::vector<Bar>&b){std::vector<ValidationIssue> e;for(size_t i=0;i<b.size();++i){auto&x=b[i];if(i&&x.timestamp<=b[i-1].timestamp)e.push_back({i,"timestamps must be strictly increasing"});if(!std::isfinite(x.open)||!std::isfinite(x.high)||!std::isfinite(x.low)||!std::isfinite(x.close)||!std::isfinite(x.volume))e.push_back({i,"non-finite value"});if(x.open<=0||x.high<=0||x.low<=0||x.close<=0)e.push_back({i,"prices must be positive"});if(x.volume<0||x.high<std::max(x.open,x.close)||x.low>std::min(x.open,x.close))e.push_back({i,"invalid OHLCV"});}return e;}void DataValidator::requireValid(const std::vector<Bar>&b){auto e=validate(b);if(!e.empty())throw std::invalid_argument(e.front().message);}std::vector<Bar> DataLoader::fromCsv(const std::string&p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open "+p);std::string line;std::getline(f,line);std::vector<Bar>o;while(std::getline(f,line)){if(line.empty())continue;std::stringstream s(line);std::string t,v;std::vector<double>a;std::getline(s,t,',');while(std::getline(s,v,','))a.push_back(std::stod(v));if(a.size()!=5)throw std::invalid_argument("CSV requires 6 columns");o.push_back({std::stoll(t),a[0],a[1],a[2],a[3],a[4]});}requireValid(o);return o;}}
namespace qte::indicators {std::vector<double>closes(const std::vector<Bar>&b){std::vector<double>r;r.reserve(b.size());for(auto&x:b)r.push_back(x.close);return r;}std::vector<double>sma(const std::vector<double>&x,size_t p){if(!p)throw std::invalid_argument("period must be positive");std::vector<double>r(x.size(),NAN);long double sum=0;for(size_t i=0;i<x.size();++i){sum+=x[i];if(i>=p)sum-=x[i-p];if(i+1>=p)r[i]=static_cast<double>(sum/p);}return r;}std::vector<double>ema(const std::vector<double>&x,size_t p){auto r=std::vector<double>(x.size(),NAN);if(!p)throw std::invalid_argument("period must be positive");if(x.size()<p)return r;double v=std::accumulate(x.begin(),x.begin()+p,0.0)/p,a=2.0/(p+1);r[p-1]=v;for(size_t i=p;i<x.size();++i)r[i]=v=a*x[i]+(1-a)*v;return r;}std::vector<double>simpleReturns(const std::vector<double>&x){std::vector<double>r(x.size(),NAN);for(size_t i=1;i<x.size();++i)r[i]=x[i-1]?x[i]/x[i-1]-1:NAN;return r;}std::vector<double>logReturns(const std::vector<double>&x){std::vector<double>r(x.size(),NAN);for(size_t i=1;i<x.size();++i)r[i]=std::log(x[i]/x[i-1]);return r;}std::vector<double>rsi(const std::vector<double>&x,size_t p){if(!p)throw std::invalid_argument("period must be positive");std::vector<double>r(x.size(),NAN);if(x.size()<=p)return r;double gain=0,loss=0;for(size_t i=1;i<=p;++i){double d=x[i]-x[i-1];gain+=std::max(0.0,d);loss+=std::max(0.0,-d);}gain/=p;loss/=p;for(size_t i=p;i<x.size();++i){if(i>p){double d=x[i]-x[i-1];gain=(gain*(p-1)+std::max(0.0,d))/p;loss=(loss*(p-1)+std::max(0.0,-d))/p;}r[i]=loss==0?100:100-100/(1+gain/loss);}return r;}std::vector<double>rollingVolatility(const std::vector<double>&x,size_t p,double annual){if(p<2)throw std::invalid_argument("volatility period must be >=2");auto ret=simpleReturns(x);std::vector<double>r(x.size(),NAN);for(size_t i=p;i<x.size();++i){double m=0;for(size_t j=i-p+1;j<=i;++j)m+=ret[j];m/=p;double v=0;for(size_t j=i-p+1;j<=i;++j)v+=(ret[j]-m)*(ret[j]-m);r[i]=std::sqrt(v/(p-1))*std::sqrt(annual);}return r;}}
namespace qte {MomentumStrategy::MomentumStrategy(size_t f,size_t s):fast_(f),slow_(s){if(!f||f>=s)throw std::invalid_argument("fast period must be positive and less than slow period");}Signal MomentumStrategy::generateSignal(const std::vector<Bar>&b,size_t i)const{if(i>=b.size()||i+1<slow_)return Signal::Hold;auto c=indicators::closes(b);auto f=indicators::sma(c,fast_),s=indicators::sma(c,slow_);return f[i]>s[i]?Signal::Buy:f[i]<s[i]?Signal::Sell:Signal::Hold;}MeanReversionStrategy::MeanReversionStrategy(size_t p,double t):period_(p),threshold_(t){if(!p||t<=0)throw std::invalid_argument("invalid mean reversion parameters");}Signal MeanReversionStrategy::generateSignal(const std::vector<Bar>&b,size_t i)const{if(i>=b.size()||i+1<period_)return Signal::Hold;auto c=indicators::closes(b);double m=0;for(size_t j=i+1-period_;j<=i;++j)m+=c[j];m/=period_;double v=0;for(size_t j=i+1-period_;j<=i;++j)v+=(c[j]-m)*(c[j]-m);double sd=std::sqrt(v/period_);if(sd==0)return Signal::Hold;double z=(c[i]-m)/sd;return z<-threshold_?Signal::Buy:z>threshold_?Signal::Sell:Signal::Hold;}PairsTradingStrategy::PairsTradingStrategy(size_t p,double h,double t):period_(p),hedgeRatio_(h),threshold_(t){}double PairsTradingStrategy::zScore(const std::vector<Bar>&a,const std::vector<Bar>&b,size_t i)const{if(a.size()!=b.size()||i>=a.size()||i+1<period_)return NAN;std::vector<double>s;for(size_t j=i+1-period_;j<=i;++j)s.push_back(a[j].close-hedgeRatio_*b[j].close);double m=std::accumulate(s.begin(),s.end(),0.0)/s.size(),v=0;for(double x:s)v+=(x-m)*(x-m);double sd=std::sqrt(v/s.size());return sd? (s.back()-m)/sd:0;}PairsTradingStrategy::PairSignal PairsTradingStrategy::generateSignal(const std::vector<Bar>&a,const std::vector<Bar>&b,size_t i)const{double z=zScore(a,b,i);return std::isnan(z)?PairSignal::Flat:z<-threshold_?PairSignal::LongSpread:z>threshold_?PairSignal::ShortSpread:PairSignal::Flat;}
namespace execution {Fill TransactionCostModel::fill(const Order&o,double p)const{double slip=p*slippage_;double ep=p+(o.side==Side::Buy?slip:-slip),notional=ep*o.quantity;return{o.side,o.quantity,p,ep,std::abs(notional)*commission_,std::abs(o.quantity*slip)};}}
namespace portfolio {void Portfolio::apply(long long ts,const std::string&sym,const execution::Fill&f){auto&pos=positions_[sym];double signedQty=f.side==execution::Side::Buy?f.quantity:-f.quantity;double realized=0;if(signedQty<0&&pos.quantity>0){double closing=std::min(pos.quantity,-signedQty);realized=(f.executionPrice-pos.averagePrice)*closing;pos.realizedPnl+=realized;}cash_-=signedQty*f.executionPrice+f.commission_;pos.quantity+=signedQty;if(pos.quantity>0)pos.averagePrice=(pos.averagePrice*(pos.quantity-signedQty)+f.executionPrice*signedQty)/pos.quantity;ledger_.push_back({ts,sym,f.side,f.quantity,f.executionPrice,f.commission_,f.slippage_,realized});}double Portfolio::equity(double price)const{return cash_+quantity()*price;}double Portfolio::quantity(const std::string&s)const{auto i=positions_.find(s);return i==positions_.end()?0:i->second.quantity;}}
BacktestResult Backtester::run(const std::vector<Bar>&b,const Strategy&s,const BacktestConfig&c){data::DataValidator::requireValid(b);if(c.initialCapital<=0)throw std::invalid_argument("initial capital must be positive");size_t n=c.maxBars?std::min(c.maxBars,b.size()):b.size();BacktestResult r;if(!n){r.equity={c.initialCapital};r.finalCapital=c.initialCapital;return r;}portfolio::Portfolio p(c.initialCapital);execution::ExecutionEngine ex(execution::TransactionCostModel(c.commissionRate,c.slippageRate));risk::RiskManager rm({c.maxPositionFraction,1,c.maxDrawdown,1});Signal pending=Signal::Hold;double peak=c.initialCapital;for(size_t i=0;i<n;++i){if(pending!=Signal::Hold){double px=b[i].open,desired=c.initialCapital*c.maxPositionFraction/px,current=p.quantity(),dq=pending==Signal::Buy?desired-current:-desired-current;if(std::abs(dq)>1e-12&&rm.allowsNewPosition(p.equity(px),std::abs(dq*px),peak)){auto fill=ex.execute({dq>0?execution::Side::Buy:execution::Side::Sell,std::abs(dq)},px);p.apply(b[i].timestamp,"DEFAULT",fill);r.trades.push_back({b[i].timestamp,dq>0?Signal::Buy:Signal::Sell,std::abs(dq),fill.executionPrice,fill.commission,fill.slippage,0});}}double eq=p.equity(b[i].close);peak=std::max(peak,eq);r.equity.push_back(eq);if(i+1<n)pending=s.generateSignal(b,i);}r.finalCapital=r.equity.back();return r;}
PerformanceMetrics PerformanceAnalyzer::analyze(const BacktestResult&r,double initial,double rf){PerformanceMetrics m;if(r.equity.empty())return m;m.totalReturn=r.finalCapital/initial-1;double years=r.equity.size()/252.0;m.cagr=years>0?std::pow(r.finalCapital/initial,1/years)-1:0;std::vector<double>x;for(size_t i=1;i<r.equity.size();++i)x.push_back(r.equity[i]/r.equity[i-1]-1);double mean=x.empty()?0:std::accumulate(x.begin(),x.end(),0.0)/x.size(),v=0,down=0;for(double z:x){v+=(z-mean)*(z-mean);if(z<0)down+=z*z;}m.annualizedVolatility=x.size()>1?std::sqrt(v/(x.size()-1)*252):0;m.sharpe=m.annualizedVolatility?(mean*252-rf)/m.annualizedVolatility:0;m.sortino=down?mean*252/std::sqrt(down/x.size()*252):0;double peak=initial;for(double e:r.equity){peak=std::max(peak,e);m.maximumDrawdown=std::min(m.maximumDrawdown,e/peak-1);}m.calmar=m.maximumDrawdown?m.cagr/std::abs(m.maximumDrawdown):0;m.numberOfTrades=r.trades.size();double wins=0,gp=0,gl=0;for(auto&t:r.trades){m.totalFees+=t.fees;m.totalSlippage+=t.slippage;if(t.realizedPnl>0){++wins;gp+=t.realizedPnl;}else gl-=t.realizedPnl;}m.winRate=m.numberOfTrades?wins/m.numberOfTrades:0;m.profitFactor=gl?gp/gl:0;m.averageTrade=m.numberOfTrades?(gp-gl)/m.numberOfTrades:0;return m;}void PerformanceAnalyzer::writeEquity(const BacktestResult&r,const std::string&p){std::ofstream f(p);f<<"index,equity\n";for(size_t i=0;i<r.equity.size();++i)f<<i<<","<<r.equity[i]<<"\n";}void PerformanceAnalyzer::writeCsv(const PerformanceMetrics&m,const std::string&p){std::ofstream f(p);f<<"metric,value\n"<<"total_return,"<<m.totalReturn<<"\ncagr,"<<m.cagr<<"\nannualized_volatility,"<<m.annualizedVolatility<<"\nsharpe,"<<m.sharpe<<"\nsortino,"<<m.sortino<<"\nmaximum_drawdown,"<<m.maximumDrawdown<<"\ncalmar,"<<m.calmar<<"\nwin_rate,"<<m.winRate<<"\nprofit_factor,"<<m.profitFactor<<"\nnumber_of_trades,"<<m.numberOfTrades<<"\ntotal_fees,"<<m.totalFees<<"\ntotal_slippage,"<<m.totalSlippage<<"\n";}}
