#include "data/MarketData.hpp"
#include "indicators/Indicators.hpp"
#include "strategy/Strategy.hpp"
#include "backtest/BacktestEngine.hpp"
#include "performance/PerformanceAnalyzer.hpp"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <numeric>
#include <sstream>
#include <stdexcept>
namespace qte {
std::vector<std::string> DataValidator::validate(const std::vector<Bar>& b){std::vector<std::string> e; for(size_t i=0;i<b.size();++i){auto &x=b[i]; if(i&&x.timestamp<=b[i-1].timestamp)e.push_back("timestamps must be strictly increasing at index "+std::to_string(i)); if(x.timestamp<0)e.push_back("negative timestamp"); if(!std::isfinite(x.open)||!std::isfinite(x.high)||!std::isfinite(x.low)||!std::isfinite(x.close)||!std::isfinite(x.volume))e.push_back("non-finite value"); if(x.open<=0||x.high<=0||x.low<=0||x.close<=0)e.push_back("prices must be positive"); if(x.volume<0||x.high<std::max(x.open,x.close)||x.low>std::min(x.open,x.close))e.push_back("invalid OHLCV at index "+std::to_string(i));} return e;}
void DataValidator::requireValid(const std::vector<Bar>& b){auto e=validate(b);if(!e.empty())throw std::invalid_argument(e.front());}
std::vector<Bar> DataLoader::fromCsv(const std::string& p){std::ifstream f(p);if(!f)throw std::runtime_error("cannot open "+p);std::string line;std::getline(f,line);std::vector<Bar> out;while(std::getline(f,line)){if(line.empty())continue;std::stringstream s(line);std::string v;std::vector<double> a;std::string t;std::getline(s,t,',');while(std::getline(s,v,','))a.push_back(std::stod(v));if(a.size()!=5)throw std::invalid_argument("expected timestamp,open,high,low,close,volume");out.push_back({std::stoll(t),a[0],a[1],a[2],a[3],a[4]});}DataValidator::requireValid(out);return out;}
namespace indicators { std::vector<double> sma(const std::vector<double>&x,size_t p){if(!p)throw std::invalid_argument("period");std::vector<double> o(x.size(),NAN);double sum=0;for(size_t i=0;i<x.size();++i){sum+=x[i];if(i>=p)sum-=x[i-p];if(i+1>=p)o[i]=sum/p;}return o;} std::vector<double> ema(const std::vector<double>&x,size_t p){if(!p)throw std::invalid_argument("period");std::vector<double>o(x.size(),NAN);if(x.size()<p)return o;double a=2.0/(p+1),v=std::accumulate(x.begin(),x.begin()+p,0.0)/p;o[p-1]=v;for(size_t i=p;i<x.size();++i)o[i]=v=a*x[i]+(1-a)*v;return o;} std::vector<double> simpleReturns(const std::vector<double>&x){std::vector<double>o(x.size(),NAN);for(size_t i=1;i<x.size();++i)o[i]=x[i]/x[i-1]-1;return o;} std::vector<double> logReturns(const std::vector<double>&x){std::vector<double>o(x.size(),NAN);for(size_t i=1;i<x.size();++i)o[i]=std::log(x[i]/x[i-1]);return o;} std::vector<double> rsi(const std::vector<double>&x,size_t p){auto o=std::vector<double>(x.size(),NAN);if(p==0||x.size()<=p)return o;double g=0,l=0;for(size_t i=1;i<=p;++i){double d=x[i]-x[i-1];g+=std::max(0.0,d);l+=std::max(0.0,-d);}for(size_t i=p;i<x.size();++i){if(i>p){double d=x[i]-x[i-1];g=(g*(p-1)+std::max(0.0,d))/p;l=(l*(p-1)+std::max(0.0,-d))/p;}o[i]=l==0?100:100-100/(1+g/l);}return o;} std::vector<double> volatility(const std::vector<double>&x,size_t p){auto r=simpleReturns(x),o(x.size(),NAN);for(size_t i=p;i<x.size();++i){double m=0;for(size_t j=i-p+1;j<=i;++j)m+=r[j];m/=p;double v=0;for(size_t j=i-p+1;j<=i;++j)v+=(r[j]-m)*(r[j]-m);o[i]=std::sqrt(v/(p-1))*std::sqrt(252.0);}return o;} std::vector<double> closes(const std::vector<Bar>&b){std::vector<double>o;for(auto&x:b)o.push_back(x.close);return o;} }
Signal MomentumStrategy::signal(const std::vector<Bar>&b,size_t i)const{if(i+1<slow_)return Signal::Hold;auto c=indicators::closes(b);auto f=indicators::sma(c,fast_),s=indicators::sma(c,slow_);return f[i]>s[i]?Signal::Buy:f[i]<s[i]?Signal::Sell:Signal::Hold;}
Signal MeanReversionStrategy::signal(const std::vector<Bar>&b,size_t i)const{if(i+1<period_)return Signal::Hold;auto c=indicators::closes(b);double m=0;for(size_t j=i+1-period_;j<=i;++j)m+=c[j];m/=period_;double v=0;for(size_t j=i+1-period_;j<=i;++j)v+=(c[j]-m)*(c[j]-m);double sd=std::sqrt(v/period_);if(sd==0)return Signal::Hold;double z=(c[i]-m)/sd;return z<-threshold_?Signal::Buy:z>threshold_?Signal::Sell:Signal::Hold;}
BacktestResult Backtester::run(const std::vector<Bar>&b,const Strategy&s,const BacktestConfig&c){DataValidator::requireValid(b);if(b.empty())return {{c.initialCapital},{},c.initialCapital};size_t n=c.maxBars?std::min(c.maxBars,b.size()):b.size();double cash=c.initialCapital,qty=0,entry=0;BacktestResult r;r.equity.reserve(n);std::vector<Signal> pending(n,Signal::Hold);for(size_t i=0;i<n;++i){if(pending[i]!=Signal::Hold&&i>0){auto side=pending[i];double px=b[i].open*(side==Signal::Buy?1+c.slippageRate:1-c.slippageRate),desired=c.initialCapital*c.maxPositionFraction/px;double dq=side==Signal::Buy?desired-qty:-desired-qty;if(std::abs(dq)>1e-12){double fees=std::abs(dq*px)*c.commissionRate;double realized=dq<0?(px-entry)*std::min(qty,-dq):0;cash-=dq*px+fees;r.trades.push_back({b[i].timestamp,side,std::abs(dq),px,fees,std::abs(dq*px)*c.slippageRate,realized});qty+=dq;if(qty>0)entry=px;}}double eq=cash+qty*b[i].close;r.equity.push_back(eq);if(i+1<n)pending[i+1]=s.signal(b,i);}r.finalCapital=r.equity.back();return r;}
Metrics PerformanceAnalyzer::analyze(const BacktestResult&r,double initial,double rf){Metrics m;if(r.equity.empty())return m;m.totalReturn=r.finalCapital/initial-1;double years=r.equity.size()/252.0;m.cagr=years>0?std::pow(r.finalCapital/initial,1/years)-1:0;std::vector<double>x;for(size_t i=1;i<r.equity.size();++i)x.push_back(r.equity[i]/r.equity[i-1]-1);double mean=x.empty()?0:std::accumulate(x.begin(),x.end(),0.0)/x.size(),v=0;for(double z:x)v+=(z-mean)*(z-mean);m.annualVolatility=x.size()>1?std::sqrt(v/(x.size()-1))*std::sqrt(252.0):0;m.sharpe=m.annualVolatility?(mean*252-rf)/m.annualVolatility:0;double peak=initial,down=0;for(double e:r.equity){peak=std::max(peak,e);down=std::min(down,e/peak-1);}m.maxDrawdown=down;m.calmar=down?m.cagr/std::abs(down):0;m.trades=r.trades.size();double wins=0,gp=0,gl=0;for(auto&t:r.trades){m.totalFees+=t.fees;m.totalSlippage+=t.slippage;if(t.realizedPnl>0){wins++;gp+=t.realizedPnl;}else gl-=t.realizedPnl;}m.winRate=m.trades?wins/m.trades:0;m.profitFactor=gl?gp/gl:0;m.averageTrade=m.trades?(gp-gl)/m.trades:0;return m;}
void PerformanceAnalyzer::writeEquity(const BacktestResult&r,const std::string&p){std::ofstream f(p);f<<"index,equity\n";for(size_t i=0;i<r.equity.size();++i)f<<i<<","<<std::setprecision(15)<<r.equity[i]<<"\n";}
void PerformanceAnalyzer::writeCsv(const Metrics&m,const std::string&p){std::ofstream f(p);f<<"metric,value\n";f<<"total_return,"<<m.totalReturn<<"\ncagr,"<<m.cagr<<"\nannual_volatility,"<<m.annualVolatility<<"\nsharpe,"<<m.sharpe<<"\nmax_drawdown,"<<m.maxDrawdown<<"\nwin_rate,"<<m.winRate<<"\nprofit_factor,"<<m.profitFactor<<"\ntrades,"<<m.trades<<"\ntotal_fees,"<<m.totalFees<<"\ntotal_slippage,"<<m.totalSlippage<<"\n";}
}
